In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

In [8]:
data_fake=pd.read_csv("Fake.csv")
data_true=pd.read_csv("True.csv")

In [9]:
data_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [10]:
data_fake['class']=0
data_true['class']=1

In [12]:
data_fake.head()

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [20]:
data_fake_manual_training=data_fake.tail(10)
for i in range(23480,23470,-1):
    data_fake.drop([i],axis=0, inplace= True)

data_true_manual_training=data_true.tail(10)
for i in range(21416,21405,-1):
    data_true.drop([i],axis=0, inplace= True)

KeyError: '[23480] not found in axis'

In [21]:
data_fake.shape, data_true.shape

((23471, 5), (21406, 5))

In [22]:
data_fake_manual_training['class']=0
data_true_manual_training['class']=1

/var/folders/vy/fch6w1_x1l75t7_9zqnljtt80000gn/T/ipykernel_5426/1157990448.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_fake_manual_training['class']=0
/var/folders/vy/fch6w1_x1l75t7_9zqnljtt80000gn/T/ipykernel_5426/1157990448.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_true_manual_training['class']=1

In [23]:
data_fake_manual_training.head()

,title,text,subject,date,class
23461,REPORT: ‘Federal Government Escalated the Viol...,KILLED: Rancher and protest spokesman Robert ...,Middle-east,"January 28, 2016",0
23462,"BOILER ROOM – Oregon Standoff, Cuddle Parties,...",Tune in to the Alternate Current Radio Network...,Middle-east,"January 28, 2016",0
23463,"Eyewitness Says Feds Ambushed Bundys, 100 Shot...",Patrick Henningsen 21st Century Wire UPDATE: 1...,Middle-east,"January 27, 2016",0
23464,Episode #119 – SUNDAY WIRE: ‘You Know the Dril...,Episode #119 of SUNDAY WIRE SHOW finally resum...,Middle-east,"January 24, 2016",0
23465,‘There’ll be boots on the ground’: US making n...,21st Century Wire says Various parties in Wash...,Middle-east,"January 23, 2016",0

In [24]:
data_true_manual_training.head()

,title,text,subject,date,class
21407,"Mata Pires, owner of embattled Brazil builder ...","SAO PAULO (Reuters) - Cesar Mata Pires, the ow...",worldnews,"August 22, 2017",1
21408,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21409,"U.S., North Korea clash at U.N. arms forum on ...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21410,Headless torso could belong to submarine journ...,COPENHAGEN (Reuters) - Danish police said on T...,worldnews,"August 22, 2017",1
21411,North Korea shipments to Syria chemical arms a...,UNITED NATIONS (Reuters) - Two North Korean sh...,worldnews,"August 21, 2017",1

In [30]:
data_merge=pd.concat([data_fake,data_true],axis=0)
data_merge.tail(10)

,title,text,subject,date,class
21396,Pro-Houthi fighters call powerful Yemen ally '...,DUBAI (Reuters) - Fighters loyal to the armed ...,worldnews,"August 23, 2017",1
21397,Germany's Schulz says he would demand U.S. wit...,BERLIN (Reuters) - The leader of Germany s Soc...,worldnews,"August 23, 2017",1
21398,Blunt instrument? What a list of banned articl...,SHANGHAI (Reuters) - An old review of an acade...,worldnews,"August 23, 2017",1
21399,Saudi police release teenager detained for dan...,DUBAI (Reuters) - A 14-year-old boy who was de...,worldnews,"August 22, 2017",1
21400,"The People's Princess, Britons work to keep me...",LONDON (Reuters) - Abdul Daoud spilt most of t...,worldnews,"August 23, 2017",1
21401,"Argentina labor unions protest job losses, Mac...",BUENOS AIRES (Reuters) - Argentina s main labo...,worldnews,"August 22, 2017",1
21402,Exclusive: Trump's Afghan decision may increas...,ON BOARD A U.S. MILITARY AIRCRAFT (Reuters) - ...,worldnews,"August 22, 2017",1
21403,U.S. puts more pressure on Pakistan to help wi...,WASHINGTON (Reuters) - The United States sugge...,worldnews,"August 21, 2017",1
21404,Exclusive: U.S. to withhold up to $290 million...,WASHINGTON (Reuters) - The United States has d...,worldnews,"August 22, 2017",1
21405,Trump talks tough on Pakistan's 'terrorist' ha...,ISLAMABAD (Reuters) - Outlining a new strategy...,worldnews,"August 22, 2017",1

In [28]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [33]:
data=data_merge.drop(['title','subject','date'],axis=1)

In [34]:
data

                                                    text  class
0      Donald Trump just couldn t wish all Americans ...      0
1      House Intelligence Committee Chairman Devin Nu...      0
2      On Friday, it was revealed that former Milwauk...      0
3      On Christmas day, Donald Trump announced that ...      0
4      Pope Francis used his annual Christmas Day mes...      0
...                                                  ...    ...
21401  BUENOS AIRES (Reuters) - Argentina s main labo...      1
21402  ON BOARD A U.S. MILITARY AIRCRAFT (Reuters) - ...      1
21403  WASHINGTON (Reuters) - The United States sugge...      1
21404  WASHINGTON (Reuters) - The United States has d...      1
21405  ISLAMABAD (Reuters) - Outlining a new strategy...      1

[44877 rows x 2 columns]

In [35]:
data.isnull().sum()

text     0
class    0
dtype: int64

In [36]:
data=data.sample(frac=1)

In [37]:
data.head()

                                                    text  class
14198  JAKARTA (Reuters) - Indonesia s Mount Agung vo...      1
19936  WASHINGTON (Reuters) - White House national se...      1
4334   PALM BEACH, Fla. (Reuters) - President Donald ...      1
22820  Andrew Korybko The DuranTrump was more aggress...      0
15186  SEOUL (Reuters) - South Korea will join three ...      1

In [40]:
data.reset_index(inplace=True)
data.drop(['index'],axis=1,inplace=True)

In [41]:
data.head()

                                                text  class
0  JAKARTA (Reuters) - Indonesia s Mount Agung vo...      1
1  WASHINGTON (Reuters) - White House national se...      1
2  PALM BEACH, Fla. (Reuters) - President Donald ...      1
3  Andrew Korybko The DuranTrump was more aggress...      0
4  SEOUL (Reuters) - South Korea will join three ...      1

In [47]:
def wordopt(text):
    text=text.lower()
    text=re.sub('\[.*?\]','',text)
    text=re.sub('\\W'," ", text)
    text=re.sub('https?://\S+|www\.\S+', '', text)
    text=re.sub('<.*?>+', '' ,text)
    text=re.sub('[%s]'%re.escape(string.punctuation),'',text)
    text=re.sub('\n', '',text)
    text=re.sub('\w*\d\w*','', text)
    return text

<>:3: SyntaxWarning: invalid escape sequence '\['
<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\['
<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
/var/folders/vy/fch6w1_x1l75t7_9zqnljtt80000gn/T/ipykernel_5426/894041182.py:3: SyntaxWarning: invalid escape sequence '\['
  text=re.sub('\[.*?\]','',text)
/var/folders/vy/fch6w1_x1l75t7_9zqnljtt80000gn/T/ipykernel_5426/894041182.py:5: SyntaxWarning: invalid escape sequence '\S'
  text=re.sub('https?://\S+|www\.\S+', '', text)
/var/folders/vy/fch6w1_x1l75t7_9zqnljtt80000gn/T/ipykernel_5426/894041182.py:9: SyntaxWarning: invalid escape sequence '\w'
  text=re.sub('\w*\d\w*','', text)

In [48]:
data['text']=data['text'].apply(wordopt)

In [49]:
data.head()

                                                text  class
0  jakarta  reuters    indonesia s mount agung vo...      1
1  washington  reuters    white house national se...      1
2  palm beach  fla   reuters    president donald ...      1
3  andrew korybko the durantrump was more aggress...      0
4  seoul  reuters    south korea will join three ...      1

In [50]:
x=data['text']
y=data['class']

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization= TfidfVectorizer()

xv_train=vectorization.fit_transform(x_train)
xv_test= vectorization.transform(x_test)

In [57]:
from sklearn.linear_model import LogisticRegression

In [59]:
lr=LogisticRegression()
lr.fit(xv_train,y_train)

LogisticRegression()

In [60]:
pred_lr=lr.predict(xv_test)

In [61]:
lr.score(xv_test,y_test)

0.9861853832442068

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5959
           1       0.98      0.99      0.99      5261

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [63]:
from sklearn.tree import DecisionTreeClassifier

In [65]:
dt=DecisionTreeClassifier()
dt.fit(xv_train,y_train)

DecisionTreeClassifier()

In [66]:
dt_pred=dt.predict(xv_test)

In [67]:
dt.score(xv_test,y_test)

0.9959001782531194

In [83]:
def output_lable(n):
    if n==0:
        return 'Fake News'
    if n ==1:
        return 'Not a fake news'
    
def manual_testing(news):
    testing_news={'text':[news]}
    new_def_test=pd.DataFrame(testing_news)
    new_def_test['text']=new_def_test['text'].apply(wordopt)
    new_x_test=new_def_test['text']
    new_xv_test=vectorization.transform(new_x_test)

    pred_lr=lr.predict(new_xv_test)
    pred_dt=dt.predict(new_xv_test)

    return print('\n Logistic Regiression Prediction: {} \n Decision Tree Prediction: {}'.format(output_lable(pred_lr[0]),output_lable(pred_dt[0])))

In [85]:
news=str(input())
manual_testing(news)

 Logistic Regiression Prediction: Not a fake news
 Decision Tree Prediction: Fake News

In [86]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5959
           1       0.98      0.99      0.99      5261

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220